version: '3.8'

services:
  prefiller:
    image: iaas-gpu-cn-beijing.cr.volces.com/serving/xllm:private_xllm_th24_cu124_xperf_0609
    container_name: prefiller
    restart: unless-stopped
    network_mode: host
    userns_mode: host
    privileged: true
    shm_size: 128g
    stdin_open: true
    tty: true
    command: ["bash", "/app/prefiller-setup"]
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'private_xllm.bin' && (echo > /dev/tcp/localhost/62000) 2>/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
    volumes:
      - /data00/models/DeepSeek-R1-ENC-xLLM:/data/models/DeepSeek-R1-ENC-xLLM
      - /data00/models/DeepSeek-R1-DRAFT-ENC-xLLM:/data/models/DeepSeek-R1-DRAFT-ENC-xLLM
      - /root/license.lic:/app/xllm/license.lic
      - /root/prefill_enc.env:/app/xllm/prefill_enc.env
      - /var/run/nvidia-topologyd/:/var/run/nvidia-topologyd/
      - ./prefiller-setup:/app/prefiller-setup:ro

  decoder:
    image: iaas-gpu-cn-beijing.cr.volces.com/serving/xllm:private_xllm_th24_cu124_xperf_0609
    container_name: decoder
    restart: unless-stopped
    network_mode: host
    userns_mode: host
    privileged: true
    shm_size: 128g
    stdin_open: true
    tty: true
    command: ["bash", "/app/decoder-setup"]
    environment:
      - PREFILL_NODE_IP=${PREFILL_NODE_IP}
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'private_xllm.bin' && curl -f http://localhost/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 180s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
    volumes:
      - /data00/models/DeepSeek-R1-ENC-xLLM:/data/models/DeepSeek-R1-ENC-xLLM
      - /data00/models/DeepSeek-R1-DRAFT-ENC-xLLM:/data/models/DeepSeek-R1-DRAFT-ENC-xLLM
      - /root/license.lic:/app/xllm/license.lic
      - /root/decode_enc.env:/app/xllm/decode_enc.env
      - /var/run/nvidia-topologyd/:/var/run/nvidia-topologyd/
      - ./decoder-setup:/app/decoder-setup:ro
      - .:/app/api-server:ro 