# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto.ark_pb2 as ark__pb2


class InferenceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Call = channel.unary_unary(
            "/inference.Inference/Call",
            request_serializer=ark__pb2.InferenceRequest.SerializeToString,
            response_deserializer=ark__pb2.InferenceResponse.FromString,
        )
        self.StreamingCall = channel.unary_stream(
            "/inference.Inference/StreamingCall",
            request_serializer=ark__pb2.InferenceRequest.SerializeToString,
            response_deserializer=ark__pb2.InferenceResponse.FromString,
        )
        self.Control = channel.unary_unary(
            "/inference.Inference/Control",
            request_serializer=ark__pb2.ControlRequest.SerializeToString,
            response_deserializer=ark__pb2.ControlResponse.FromString,
        )
        self.DistributeCall = channel.unary_unary(
            "/inference.Inference/DistributeCall",
            request_serializer=ark__pb2.InferenceRequest.SerializeToString,
            response_deserializer=ark__pb2.InferenceResponse.FromString,
        )


class InferenceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Call(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StreamingCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Control(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DistributeCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_InferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Call": grpc.unary_unary_rpc_method_handler(
            servicer.Call,
            request_deserializer=ark__pb2.InferenceRequest.FromString,
            response_serializer=ark__pb2.InferenceResponse.SerializeToString,
        ),
        "StreamingCall": grpc.unary_stream_rpc_method_handler(
            servicer.StreamingCall,
            request_deserializer=ark__pb2.InferenceRequest.FromString,
            response_serializer=ark__pb2.InferenceResponse.SerializeToString,
        ),
        "Control": grpc.unary_unary_rpc_method_handler(
            servicer.Control,
            request_deserializer=ark__pb2.ControlRequest.FromString,
            response_serializer=ark__pb2.ControlResponse.SerializeToString,
        ),
        "DistributeCall": grpc.unary_unary_rpc_method_handler(
            servicer.DistributeCall,
            request_deserializer=ark__pb2.InferenceRequest.FromString,
            response_serializer=ark__pb2.InferenceResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("inference.Inference", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Inference(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Call(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/inference.Inference/Call",
            ark__pb2.InferenceRequest.SerializeToString,
            ark__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def StreamingCall(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/inference.Inference/StreamingCall",
            ark__pb2.InferenceRequest.SerializeToString,
            ark__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Control(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/inference.Inference/Control",
            ark__pb2.ControlRequest.SerializeToString,
            ark__pb2.ControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def DistributeCall(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/inference.Inference/DistributeCall",
            ark__pb2.InferenceRequest.SerializeToString,
            ark__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
